version: "3"
services:
  redis:
    image: "redis:latest"
    volumes:
      - "./redisData:/data"
  nodejs:
    build: 
      context: .
      dockerfile: "./PATServer/dockerfile"
    ports:
      - "4000:4000"
    environment:
      - "SERVER_PORT=4000"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

    