version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redisData:/data"
  nodejs:
    build: 
      context: .
      dockerfile: ./PATServer/Dockerfile
    ports:
      - "4000:4000"
    